#!/usr/bin/env python3
"""Generate LaTeX result inputs from canonical experiment JSON."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from statistics import fmean
from typing import Any


SELECTED_CASES = [
    "horizon_04_baseline",
    "horizon_16_long_wait",
    "critic_budget_002_full",
    "critic_budget_128_full",
    "observability_blind",
    "blind_undercovered_counterexample",
    "sparse_hard_group08",
]


def latex_escape(value: str) -> str:
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    return "".join(replacements.get(char, char) for char in value)


def fmt(value: float) -> str:
    return f"{value:.3f}"


def display_case_name(case_name: str) -> str:
    labels = {
        "blind_undercovered_counterexample": "blind undercov.",
        "observability_full": "obs full",
        "observability_coarse": "obs coarse",
        "observability_blind": "obs blind",
    }
    normalized = labels.get(case_name, case_name)
    normalized = normalized.replace("critic_budget_", "budget_")
    normalized = normalized.replace("group_size_", "group_")
    normalized = normalized.replace("sparse_hard_", "sparse_")
    return latex_escape(normalized.replace("_", " "))


def display_axis_name(axis: str) -> str:
    labels = {
        "critic_budget": "budget",
        "group_size": "group",
        "sparse_reward": "sparse",
        "counterexample": "ctr.",
        "observability": "obs",
    }
    return latex_escape(labels.get(axis, axis.replace("_", " ")))


def display_ci_read(evidence: str) -> str:
    labels = {
        "critic_clear": "critic",
        "group_clear": "group",
        "near_tie": "near tie",
    }
    return latex_escape(labels[evidence])


def macro_line(name: str, value: str | int | float) -> str:
    return rf"\newcommand{{\{name}}}{{{value}}}"


def build_macros(result: dict[str, Any]) -> str:
    overall = result["overall"]
    lines = [
        "% Generated by scripts/build_latex_inputs.py; do not edit by hand.",
        macro_line("DeepSeedCount", result["seed_count"]),
        macro_line("DeepCaseCount", result["case_count"]),
        macro_line("DeepMeanCriticWins", overall["critic_wins_by_mean_correlation"]),
        macro_line("DeepMeanGroupWins", overall["group_wins_by_mean_correlation"]),
        macro_line("DeepClearCriticCases", overall["clear_critic_cases_by_ci95"]),
        macro_line("DeepNearTieCases", overall["near_tie_cases_by_ci95"]),
        macro_line("DeepClearGroupCases", overall["clear_group_cases_by_ci95"]),
        macro_line("DeepMeanDeltaCorrelation", fmt(overall["mean_delta_correlation"])),
        "",
    ]
    return "\n".join(lines)


def build_table(result: dict[str, Any]) -> str:
    cases = {case["case_name"]: case for case in result["cases"]}
    lines = [
        "% Generated by scripts/build_latex_inputs.py; do not edit by hand.",
        r"\begin{tabular}{@{}lrrrrl@{}}",
        r"\toprule",
        r"Case & Group $r$ & Critic $r$ & Delta & CI & Reading \\",
        r"\midrule",
    ]
    for case_name in SELECTED_CASES:
        case = cases[case_name]
        row = " & ".join(
            [
                latex_escape(case["case_name"]),
                fmt(case["mean_group_correlation"]),
                fmt(case["mean_critic_correlation"]),
                fmt(case["mean_critic_minus_group_correlation"]),
                rf"$\pm${fmt(case['ci95_critic_minus_group_correlation'])}",
                latex_escape(case["evidence_by_ci95"].replace("_", " ")),
            ]
        )
        lines.append(row + r" \\")
    lines.extend([r"\bottomrule", r"\end{tabular}", ""])
    return "\n".join(lines)


def build_axis_summary_table(result: dict[str, Any]) -> str:
    axes: dict[str, list[dict[str, Any]]] = {}
    for case in result["cases"]:
        axes.setdefault(case["axis"], []).append(case)

    lines = [
        "% Generated by scripts/build_latex_inputs.py; do not edit by hand.",
        r"\begin{tabular}{@{}lrrrrrrr@{}}",
        r"\toprule",
        r"Axis & Cases & Group $r$ & Critic $r$ & Delta & Clear critic & Near tie & Clear group \\",
        r"\midrule",
    ]
    for axis in sorted(axes):
        cases = axes[axis]
        clear_critic = sum(1 for case in cases if case["evidence_by_ci95"] == "critic_clear")
        near_tie = sum(1 for case in cases if case["evidence_by_ci95"] == "near_tie")
        clear_group = sum(1 for case in cases if case["evidence_by_ci95"] == "group_clear")
        row = " & ".join(
            [
                latex_escape(axis),
                str(len(cases)),
                fmt(fmean(case["mean_group_correlation"] for case in cases)),
                fmt(fmean(case["mean_critic_correlation"] for case in cases)),
                fmt(
                    fmean(
                        case["mean_critic_minus_group_correlation"]
                        for case in cases
                    )
                ),
                str(clear_critic),
                str(near_tie),
                str(clear_group),
            ]
        )
        lines.append(row + r" \\")
    lines.extend([r"\bottomrule", r"\end{tabular}", ""])
    return "\n".join(lines)


def build_full_case_table(result: dict[str, Any]) -> str:
    lines = [
        "% Generated by scripts/build_latex_inputs.py; do not edit by hand.",
        r"\begin{longtable}{@{}L{3.35cm}L{1.25cm}c*{6}{r}@{}}",
        r"\caption{Full 20-seed case summary. Delta is critic $r$ minus group $r$.}\label{tab:full-case-summary}\\",
        r"\toprule",
        r"Case & Axis & Read & Group $r$ & Critic $r$ & $\Delta r$ & 95\% CI & Hit & Wait \\",
        r"\midrule",
        r"\endfirsthead",
        r"\caption[]{Full 20-seed case summary, continued.}\\",
        r"\toprule",
        r"Case & Axis & Read & Group $r$ & Critic $r$ & $\Delta r$ & 95\% CI & Hit & Wait \\",
        r"\midrule",
        r"\endhead",
        r"\midrule",
        r"\multicolumn{9}{r}{\footnotesize\emph{Continued on next page}}\\",
        r"\endfoot",
    ]
    for case in result["cases"]:
        row = " & ".join(
            [
                display_case_name(case["case_name"]),
                display_axis_name(case["axis"]),
                display_ci_read(case["evidence_by_ci95"]),
                fmt(case["mean_group_correlation"]),
                fmt(case["mean_critic_correlation"]),
                fmt(case["mean_critic_minus_group_correlation"]),
                rf"$\pm${fmt(case['ci95_critic_minus_group_correlation'])}",
                fmt(case["mean_critic_exact_state_rate"]),
                fmt(case["mean_wait_token_fraction"]),
            ]
        )
        lines.append(row + r" \\")
    lines.extend([r"\bottomrule", r"\end{longtable}", ""])
    return "\n".join(lines)


def build_raw_seed_table(result: dict[str, Any]) -> str:
    lines = [
        "% Generated by scripts/build_latex_inputs.py; do not edit by hand.",
        r"\begin{longtable}{@{}L{3.55cm}rrrrrrr@{}}",
        r"\caption{Raw case-by-seed estimator-fidelity rows from the deep matrix.}\label{tab:raw-seed-rows}\\",
        r"\toprule",
        r"Case & Seed & Group $r$ & Critic $r$ & $\Delta r$ & Hit & Success & Wait \\",
        r"\midrule",
        r"\endfirsthead",
        r"\caption[]{Raw case-by-seed estimator-fidelity rows, continued.}\\",
        r"\toprule",
        r"Case & Seed & Group $r$ & Critic $r$ & $\Delta r$ & Hit & Success & Wait \\",
        r"\midrule",
        r"\endhead",
        r"\midrule",
        r"\multicolumn{8}{r}{\footnotesize\emph{Continued on next page}}\\",
        r"\endfoot",
    ]
    for case in result["cases"]:
        for row_data in case["seed_results"]:
            row = " & ".join(
                [
                    display_case_name(case["case_name"]),
                    str(row_data["seed"]),
                    fmt(row_data["group_correlation"]),
                    fmt(row_data["critic_correlation"]),
                    fmt(row_data["critic_minus_group_correlation"]),
                    fmt(row_data["critic_exact_state_rate"]),
                    fmt(row_data["success_rate"]),
                    fmt(row_data["wait_token_fraction"]),
                ]
            )
            lines.append(row + r" \\")
        lines.append(r"\addlinespace[2pt]")
    lines.extend([r"\bottomrule", r"\end{longtable}", ""])
    return "\n".join(lines)


def build_error_seed_table(result: dict[str, Any]) -> str:
    lines = [
        "% Generated by scripts/build_latex_inputs.py; do not edit by hand.",
        r"\begin{longtable}{@{}L{3.55cm}rrrrrrr@{}}",
        r"\caption{Raw case-by-seed calibrated-error rows from the deep matrix.}\label{tab:raw-error-rows}\\",
        r"\toprule",
        r"Case & Seed & Group MSE & Critic MSE & $\Delta$ MSE & Zero-var & Wait & Success \\",
        r"\midrule",
        r"\endfirsthead",
        r"\caption[]{Raw case-by-seed calibrated-error rows, continued.}\\",
        r"\toprule",
        r"Case & Seed & Group MSE & Critic MSE & $\Delta$ MSE & Zero-var & Wait & Success \\",
        r"\midrule",
        r"\endhead",
        r"\midrule",
        r"\multicolumn{8}{r}{\footnotesize\emph{Continued on next page}}\\",
        r"\endfoot",
    ]
    for case in result["cases"]:
        for row_data in case["seed_results"]:
            row = " & ".join(
                [
                    display_case_name(case["case_name"]),
                    str(row_data["seed"]),
                    fmt(row_data["group_calibrated_mse"]),
                    fmt(row_data["critic_calibrated_mse"]),
                    fmt(row_data["critic_minus_group_calibrated_mse"]),
                    fmt(row_data["zero_variance_group_fraction"]),
                    fmt(row_data["wait_token_fraction"]),
                    fmt(row_data["success_rate"]),
                ]
            )
            lines.append(row + r" \\")
        lines.append(r"\addlinespace[2pt]")
    lines.extend([r"\bottomrule", r"\end{longtable}", ""])
    return "\n".join(lines)


VARIANCE_LABELS = {
    "reinforce_return": "REINFORCE",
    "global_baseline": "Global",
    "sibling_group_norm": "Group z",
    "leave_one_out": "LOO",
    "dense_progress_reward": "Dense reward",
    "anchor_action_contrast": "Anchor ctr.",
    "critic_td": "Critic TD",
    "sampled_mc_td": "Sampled MC",
}

VARIANCE_REDUCTION_LABELS = {
    "none": "none",
    "global/running": "global",
    "sibling group": "group",
    "anchor state group": "anchor",
    "external dense signal": "dense",
    "learned critic V(s)": "critic",
    "sampled value": "sampled",
}

CREDIT_LABELS = {
    "trajectory": "traj.",
    "step": "step",
}


def build_variance_credit_table(result: dict[str, Any]) -> str:
    lines = [
        "% Generated by scripts/build_latex_inputs.py; do not edit by hand.",
        r"\begin{tabular}{@{}llcrrrr@{}}",
        r"\toprule",
        r"Estimator & Var. & Credit & $r$ & MSE & Wait & Within \\",
        r"\midrule",
    ]
    for estimator in result["estimators"]:
        if estimator["name"] == "oracle_advantage":
            continue
        metrics = estimator["metrics"]
        row = " & ".join(
            [
                latex_escape(VARIANCE_LABELS.get(estimator["name"], estimator["label"])),
                latex_escape(
                    VARIANCE_REDUCTION_LABELS.get(
                        estimator["variance_reduction"],
                        estimator["variance_reduction"],
                    )
                ),
                latex_escape(
                    CREDIT_LABELS.get(
                        estimator["credit_assignment"],
                        estimator["credit_assignment"],
                    )
                ),
                fmt(metrics["pearson_correlation"]),
                f"{metrics['calibrated_mse']:.4f}",
                fmt(metrics["wait_to_active_abs_ratio"]),
                fmt(metrics["within_trajectory_variance"]),
            ]
        )
        lines.append(row + r" \\")
    lines.extend([r"\bottomrule", r"\end{tabular}"])
    return "\n".join(lines)


def build_length_imbalance_table(result: dict[str, Any]) -> str:
    lines = [
        "% Generated by scripts/build_latex_inputs.py; do not edit by hand.",
        r"\begin{tabular}{@{}rrrrrrrr@{}}",
        r"\toprule",
        r"$H_{\max}$ & Len gap & Wait & Group $r$ & Len-adj. $r$ & Critic $r$ & $\Delta_G$ & $\Delta_L$ \\",
        r"\midrule",
    ]
    for row_data in result["horizon_summaries"]:
        row = " & ".join(
            [
                str(row_data["max_steps"]),
                fmt(row_data["mean_group_length_range"]),
                fmt(row_data["mean_wait_token_fraction"]),
                fmt(row_data["group_total_r"]),
                fmt(row_data["group_per_token_r"]),
                fmt(row_data["critic_r"]),
                fmt(row_data["critic_minus_group_total_r"]),
                fmt(row_data["critic_minus_group_per_token_r"]),
            ]
        )
        lines.append(row + r" \\")
    lines.extend([r"\bottomrule", r"\end{tabular}"])
    return "\n".join(lines)


def build_token_cost_table(result: dict[str, Any]) -> str:
    scenario_labels = {"baseline": "base", "long_wait": "long"}
    lines = [
        "% Generated by scripts/build_latex_inputs.py; do not edit by hand.",
        r"\begin{tabular}{@{}lrrrrrrr@{}}",
        r"\toprule",
        r"Scenario & Cost & Group $r$ & Critic $r$ & $\Delta$ & CI & Wait$_G$ & Wait$_C$ \\",
        r"\midrule",
    ]
    for row_data in result["aggregate_rows"]:
        row = " & ".join(
            [
                latex_escape(scenario_labels.get(row_data["scenario"], row_data["scenario"])),
                f"{row_data['token_cost']:.2f}",
                fmt(row_data["group_r"]),
                fmt(row_data["critic_r"]),
                fmt(row_data["delta_r"]),
                fmt(row_data["delta_ci95"]),
                fmt(row_data["group_wait_leak"]),
                fmt(row_data["critic_wait_leak"]),
            ]
        )
        lines.append(row + r" \\")
    lines.extend([r"\bottomrule", r"\end{tabular}"])
    return "\n".join(lines)


def build_closed_loop_table(default: dict[str, Any], low_coverage: dict[str, Any]) -> str:
    labels = {
        "group_total": "Group",
        "group_length_norm": "Len-group",
        "critic_td": "Critic TD",
        "coverage_gated": "Cov-gated",
    }
    settings = [
        ("default", default),
        ("low cov.", low_coverage),
    ]
    lines = [
        "% Generated by scripts/build_latex_inputs.py; do not edit by hand.",
        r"\begin{tabular}{@{}llrrrrr@{}}",
        r"\toprule",
        r"Setting & Method & Init $R$ & Final $R$ & $\Delta R$ & Success & Critic frac. \\",
        r"\midrule",
    ]
    for setting, result in settings:
        for row_data in result["method_summaries"]:
            row = " & ".join(
                [
                    latex_escape(setting),
                    latex_escape(labels.get(row_data["method"], row_data["method"])),
                    fmt(row_data["initial_return"]),
                    fmt(row_data["final_return"]),
                    fmt(row_data["return_improvement"]),
                    fmt(row_data["final_success"]),
                    fmt(row_data["final_critic_fraction"]),
                ]
            )
            lines.append(row + r" \\")
        if setting != settings[-1][0]:
            lines.append(r"\addlinespace[2pt]")
    lines.extend([r"\bottomrule", r"\end{tabular}"])
    return "\n".join(lines)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--matrix-json",
        type=Path,
        default=Path("results/deep_matrix_20seed.json"),
    )
    parser.add_argument(
        "--variance-grid-json",
        type=Path,
        default=Path("results/variance_credit_grid_seed17.json"),
    )
    parser.add_argument(
        "--length-audit-json",
        type=Path,
        default=Path("results/length_imbalance_audit_seedset.json"),
    )
    parser.add_argument(
        "--token-cost-json",
        type=Path,
        default=Path("results/token_cost_sensitivity_20seed.json"),
    )
    parser.add_argument(
        "--closed-loop-json",
        type=Path,
        default=Path("results/closed_loop_credit_training_10seed.json"),
    )
    parser.add_argument(
        "--closed-loop-low-coverage-json",
        type=Path,
        default=Path("results/closed_loop_credit_training_low_coverage_10seed.json"),
    )
    parser.add_argument("--output-dir", type=Path, default=Path("paper/generated"))
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    result = json.loads(args.matrix_json.read_text())
    variance_grid = json.loads(args.variance_grid_json.read_text())
    length_audit = json.loads(args.length_audit_json.read_text())
    token_cost = json.loads(args.token_cost_json.read_text())
    closed_loop = json.loads(args.closed_loop_json.read_text())
    closed_loop_low_coverage = json.loads(args.closed_loop_low_coverage_json.read_text())
    args.output_dir.mkdir(parents=True, exist_ok=True)

    macros = args.output_dir / "result_macros.tex"
    table = args.output_dir / "deep_matrix_table.tex"
    axis_summary = args.output_dir / "axis_summary_table.tex"
    full_case = args.output_dir / "full_case_table.tex"
    raw_seed = args.output_dir / "raw_seed_table.tex"
    raw_error = args.output_dir / "raw_error_table.tex"
    variance_credit = args.output_dir / "variance_credit_table.tex"
    length_imbalance = args.output_dir / "length_imbalance_table.tex"
    token_cost_table = args.output_dir / "token_cost_table.tex"
    closed_loop_table = args.output_dir / "closed_loop_training_table.tex"
    macros.write_text(build_macros(result) + "\n")
    table.write_text(build_table(result) + "\n")
    axis_summary.write_text(build_axis_summary_table(result) + "\n")
    full_case.write_text(build_full_case_table(result) + "\n")
    raw_seed.write_text(build_raw_seed_table(result) + "\n")
    raw_error.write_text(build_error_seed_table(result) + "\n")
    variance_credit.write_text(build_variance_credit_table(variance_grid) + "\n")
    length_imbalance.write_text(build_length_imbalance_table(length_audit) + "\n")
    token_cost_table.write_text(build_token_cost_table(token_cost) + "\n")
    closed_loop_table.write_text(
        build_closed_loop_table(closed_loop, closed_loop_low_coverage) + "\n"
    )

    print(f"wrote {macros}")
    print(f"wrote {table}")
    print(f"wrote {axis_summary}")
    print(f"wrote {full_case}")
    print(f"wrote {raw_seed}")
    print(f"wrote {raw_error}")
    print(f"wrote {variance_credit}")
    print(f"wrote {length_imbalance}")
    print(f"wrote {token_cost_table}")
    print(f"wrote {closed_loop_table}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
