#!/usr/bin/env python3
"""Generate LaTeX result inputs from canonical experiment JSON."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


SELECTED_CASES = [
    "horizon_04_baseline",
    "horizon_16_long_wait",
    "critic_budget_002_full",
    "critic_budget_128_full",
    "observability_blind",
    "blind_undercovered_counterexample",
    "sparse_hard_group08",
]


def latex_escape(value: str) -> str:
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    return "".join(replacements.get(char, char) for char in value)


def fmt(value: float) -> str:
    return f"{value:.3f}"


def fmt_pm(value: float, interval: float) -> str:
    return f"{value:.3f}$\\pm${interval:.3f}"


def fmt_pm4(value: float, interval: float) -> str:
    return f"{value:.4f}$\\pm${interval:.4f}"


def display_case_name(case_name: str) -> str:
    labels = {
        "blind_undercovered_counterexample": "blind undercov.",
        "observability_full": "obs full",
        "observability_coarse": "obs coarse",
        "observability_blind": "obs blind",
    }
    normalized = labels.get(case_name, case_name)
    normalized = normalized.replace("critic_budget_", "budget_")
    normalized = normalized.replace("group_size_", "group_")
    normalized = normalized.replace("sparse_hard_", "sparse_")
    return latex_escape(normalized.replace("_", " "))


def display_ci_read(evidence: str) -> str:
    labels = {
        "critic_clear": "critic",
        "group_clear": "group",
        "near_tie": "near tie",
    }
    return latex_escape(labels[evidence])


def macro_line(name: str, value: str | int | float) -> str:
    return rf"\newcommand{{\{name}}}{{{value}}}"


def build_macros(result: dict[str, Any]) -> str:
    overall = result["overall"]
    lines = [
        "% Generated by scripts/build_latex_inputs.py; do not edit by hand.",
        macro_line("DeepSeedCount", result["seed_count"]),
        macro_line("DeepCaseCount", result["case_count"]),
        macro_line("DeepMeanCriticWins", overall["critic_wins_by_mean_correlation"]),
        macro_line("DeepMeanGroupWins", overall["group_wins_by_mean_correlation"]),
        macro_line("DeepClearCriticCases", overall["clear_critic_cases_by_ci95"]),
        macro_line("DeepNearTieCases", overall["near_tie_cases_by_ci95"]),
        macro_line("DeepClearGroupCases", overall["clear_group_cases_by_ci95"]),
        macro_line("DeepMeanDeltaCorrelation", fmt(overall["mean_delta_correlation"])),
        "",
    ]
    return "\n".join(lines)


def build_table(result: dict[str, Any]) -> str:
    cases = {case["case_name"]: case for case in result["cases"]}
    lines = [
        "% Generated by scripts/build_latex_inputs.py; do not edit by hand.",
        r"\begin{tabular}{@{}lrrrrl@{}}",
        r"\toprule",
        r"Case & Group $r$ & Critic $r$ & Delta & CI & Reading \\",
        r"\midrule",
    ]
    for case_name in SELECTED_CASES:
        case = cases[case_name]
        row = " & ".join(
            [
                latex_escape(case["case_name"]),
                fmt(case["mean_group_correlation"]),
                fmt(case["mean_critic_correlation"]),
                fmt(case["mean_critic_minus_group_correlation"]),
                rf"$\pm${fmt(case['ci95_critic_minus_group_correlation'])}",
                latex_escape(case["evidence_by_ci95"].replace("_", " ")),
            ]
        )
        lines.append(row + r" \\")
    lines.extend([r"\bottomrule", r"\end{tabular}", ""])
    return "\n".join(lines)


VARIANCE_LABELS = {
    "reinforce_return": "REINFORCE",
    "global_baseline": "Global",
    "sibling_group_norm": "Group z",
    "leave_one_out": "LOO",
    "dense_progress_reward": "Dense reward",
    "anchor_action_contrast": "Anchor ctr.",
    "critic_td": "Critic TD",
    "sampled_mc_td": "Sampled MC",
}

VARIANCE_REDUCTION_LABELS = {
    "none": "none",
    "global/running": "global",
    "sibling group": "group",
    "anchor state group": "anchor",
    "external dense signal": "dense",
    "learned critic V(s)": "critic",
    "sampled value": "sampled",
}

CREDIT_LABELS = {
    "trajectory": "traj.",
    "step": "step",
}


def build_variance_credit_table(result: dict[str, Any]) -> str:
    lines = [
        "% Generated by scripts/build_latex_inputs.py; do not edit by hand.",
        r"\begin{tabular}{@{}llcrrrr@{}}",
        r"\toprule",
        r"Estimator & Var. & Credit & $r$ & MSE & Wait & Within \\",
        r"\midrule",
    ]
    for estimator in result["estimators"]:
        if estimator["name"] == "oracle_advantage":
            continue
        metrics = estimator["metrics"]
        row = " & ".join(
            [
                latex_escape(VARIANCE_LABELS.get(estimator["name"], estimator["label"])),
                latex_escape(
                    VARIANCE_REDUCTION_LABELS.get(
                        estimator["variance_reduction"],
                        estimator["variance_reduction"],
                    )
                ),
                latex_escape(
                    CREDIT_LABELS.get(
                        estimator["credit_assignment"],
                        estimator["credit_assignment"],
                    )
                ),
                fmt(metrics["pearson_correlation"]),
                f"{metrics['calibrated_mse']:.4f}",
                fmt(metrics["wait_to_active_abs_ratio"]),
                fmt(metrics["within_trajectory_variance"]),
            ]
        )
        lines.append(row + r" \\")
    lines.extend([r"\bottomrule", r"\end{tabular}"])
    return "\n".join(lines)


def build_anchor_coverage_table(result: dict[str, Any]) -> str:
    lines = [
        "% Generated by scripts/build_latex_inputs.py; do not edit by hand.",
        r"\begin{tabular}{@{}rrrrrrr@{}}",
        r"\toprule",
        r"Groups & Support & Group $r$ & Anchor $r$ & Critic $r$ & $A-G$ & $C-A$ \\",
        r"\midrule",
    ]
    for row_data in result["aggregate_rows"]:
        row = " & ".join(
            [
                str(row_data["eval_groups"]),
                fmt(row_data["supported_step_fraction"]),
                fmt(row_data["sibling_r"]),
                fmt(row_data["anchor_r"]),
                fmt(row_data["critic_r"]),
                fmt(row_data["anchor_minus_sibling_r"]),
                fmt(row_data["critic_minus_anchor_r"]),
            ]
        )
        lines.append(row + r" \\")
    lines.extend([r"\bottomrule", r"\end{tabular}"])
    return "\n".join(lines)


def build_length_imbalance_table(result: dict[str, Any]) -> str:
    lines = [
        "% Generated by scripts/build_latex_inputs.py; do not edit by hand.",
        r"\begin{tabular}{@{}rrrrrrrr@{}}",
        r"\toprule",
        r"$H_{\max}$ & Len gap & Wait & Group $r$ & Len-adj. $r$ & Critic $r$ & $\Delta_G$ & $\Delta_L$ \\",
        r"\midrule",
    ]
    for row_data in result["horizon_summaries"]:
        row = " & ".join(
            [
                str(row_data["max_steps"]),
                fmt(row_data["mean_group_length_range"]),
                fmt(row_data["mean_wait_token_fraction"]),
                fmt(row_data["group_total_r"]),
                fmt(row_data["group_per_token_r"]),
                fmt(row_data["critic_r"]),
                fmt(row_data["critic_minus_group_total_r"]),
                fmt(row_data["critic_minus_group_per_token_r"]),
            ]
        )
        lines.append(row + r" \\")
    lines.extend([r"\bottomrule", r"\end{tabular}"])
    return "\n".join(lines)


def build_token_cost_table(result: dict[str, Any]) -> str:
    scenario_labels = {"baseline": "base", "long_wait": "long"}
    lines = [
        "% Generated by scripts/build_latex_inputs.py; do not edit by hand.",
        r"\begin{tabular}{@{}lrrrrrrr@{}}",
        r"\toprule",
        r"Scenario & Cost & Group $r$ & Critic $r$ & $\Delta$ & CI & Wait$_G$ & Wait$_C$ \\",
        r"\midrule",
    ]
    for row_data in result["aggregate_rows"]:
        row = " & ".join(
            [
                latex_escape(scenario_labels.get(row_data["scenario"], row_data["scenario"])),
                f"{row_data['token_cost']:.2f}",
                fmt(row_data["group_r"]),
                fmt(row_data["critic_r"]),
                fmt(row_data["delta_r"]),
                fmt(row_data["delta_ci95"]),
                fmt(row_data["group_wait_leak"]),
                fmt(row_data["critic_wait_leak"]),
            ]
        )
        lines.append(row + r" \\")
    lines.extend([r"\bottomrule", r"\end{tabular}"])
    return "\n".join(lines)


def build_closed_loop_table(default: dict[str, Any], low_coverage: dict[str, Any]) -> str:
    labels = {
        "group_total": "Group",
        "group_length_norm": "Len-group",
        "critic_td": "Critic TD",
        "coverage_gated": "Cov-gated",
    }
    settings = [
        ("default", default),
        ("low cov.", low_coverage),
    ]
    lines = [
        "% Generated by scripts/build_latex_inputs.py; do not edit by hand.",
        r"\begin{tabular}{@{}llrrrrr@{}}",
        r"\toprule",
        r"Setting & Method & Init $R$ & Final $R$ & $\Delta R$ & Success & Critic frac. \\",
        r"\midrule",
    ]
    for setting, result in settings:
        for row_data in result["method_summaries"]:
            row = " & ".join(
                [
                    latex_escape(setting),
                    latex_escape(labels.get(row_data["method"], row_data["method"])),
                    fmt(row_data["initial_return"]),
                    fmt(row_data["final_return"]),
                    fmt(row_data["return_improvement"]),
                    fmt(row_data["final_success"]),
                    fmt(row_data["final_critic_fraction"]),
                ]
            )
            lines.append(row + r" \\")
        if setting != settings[-1][0]:
            lines.append(r"\addlinespace[2pt]")
    lines.extend([r"\bottomrule", r"\end{tabular}"])
    return "\n".join(lines)


def build_neural_generalization_table(result: dict[str, Any]) -> str:
    labels = {
        "group_relative": "Group",
        "neural_critic_td": "Neural TD",
    }
    metrics = result["aggregate"]["estimators"]
    counts = result["aggregate"]["sample_counts"]
    lines = [
        "% Generated by scripts/build_latex_inputs.py; do not edit by hand.",
        r"\begin{tabular}{@{}lrrrrr@{}}",
        r"\toprule",
        r"Estimator & $r$ & MSE & Sign & Wait & Within \\",
        r"\midrule",
    ]
    for name in ["group_relative", "neural_critic_td"]:
        row_data = metrics[name]
        row = " & ".join(
            [
                latex_escape(labels[name]),
                fmt(row_data["pearson_correlation"]),
                f"{row_data['calibrated_mse']:.4f}",
                fmt(row_data["sign_accuracy"]),
                fmt(row_data["wait_to_active_abs_ratio"]),
                fmt(row_data["within_trajectory_variance"]),
            ]
        )
        lines.append(row + r" \\")
    lines.append(r"\midrule")
    lines.append(
        r"\multicolumn{6}{@{}l@{}}{\footnotesize Eval keys unseen in tabular train: "
        + fmt(counts["heldout_exact_state_fraction"])
        + r"; neural minus group $r$: "
        + fmt(result["aggregate"]["neural_minus_group_correlation"])
        + r".}\\"
    )
    lines.extend([r"\bottomrule", r"\end{tabular}"])
    return "\n".join(lines)


def build_sequence_policy_table(result: dict[str, Any]) -> str:
    labels = {
        "group_broadcast": "Group",
        "neural_value_td": "Neural TD",
    }
    lines = [
        "% Generated by scripts/build_latex_inputs.py; do not edit by hand.",
        r"\begin{tabular}{@{}lrrrrr@{}}",
        r"\toprule",
        r"Method & Init $R$ & Final $R$ & $\Delta R$ & Success & Wait \\",
        r"\midrule",
    ]
    for row_data in result["method_summaries"]:
        row = " & ".join(
            [
                latex_escape(labels.get(row_data["method"], row_data["method"])),
                fmt(row_data["initial_return"]),
                fmt(row_data["final_return"]),
                fmt(row_data["return_improvement"]),
                fmt(row_data["final_success"]),
                fmt(row_data["final_wait_fraction"]),
            ]
        )
        lines.append(row + r" \\")
    lines.append(r"\midrule")
    lines.append(
        r"\multicolumn{6}{@{}p{0.88\linewidth}@{}}{\footnotesize Shared "
        r"autoregressive MLP policy; $\Delta R_{\mathrm{TD}-\mathrm{group}}="
        + fmt(result["summary"]["neural_minus_group_return"])
        + r"$; $\Delta$wait$_{\mathrm{TD}-\mathrm{group}}="
        + fmt(result["summary"]["neural_minus_group_wait_fraction"])
        + r"$.}\\"
    )
    lines.extend([r"\bottomrule", r"\end{tabular}"])
    return "\n".join(lines)


PHASE_SELECTED_ROWS = [
    "h005_non_privileged_high_contrast_matched",
    "h015_non_privileged_high_contrast_matched",
    "h030_non_privileged_low_contrast_matched",
    "h050_non_privileged_high_contrast_matched",
    "h070_blind_low_contrast_matched",
    "h090_blind_low_contrast_matched",
]


MECHANISM_LABELS = {
    "group_or_global": "group/global",
    "either_by_cost": "either; choose by cost",
    "critic_or_sampled_value": "critic/sampled value",
    "process_structural_or_hybrid": "process/structural/hybrid",
}


def build_credit_phase_table(result: dict[str, Any]) -> str:
    rows = {row["cell_name"]: row for row in result["aggregate_rows"]}
    lines = [
        "% Generated by scripts/build_latex_inputs.py; do not edit by hand.",
        r"\begin{tabularx}{\linewidth}{@{}L{3.05cm}rrrrrY@{}}",
        r"\toprule",
        r"Regime & $H_{\mathrm{credit}}$ & Ceiling & Group $r$ & Critic $r$ & $\Delta r$ & Crossover reading \\",
        r"\midrule",
    ]
    for row_name in PHASE_SELECTED_ROWS:
        row_data = rows[row_name]
        regime_label = (
            f"realized H={row_data['credit_heterogeneity']:.2f} "
            f"{'nonpriv' if row_data['observability'] == 'non_privileged' else row_data['observability']} "
            f"{row_data['coverage']} cov."
        )
        reading = (
            row_data["evidence_by_ci95"].replace("_", " ")
            + "; "
            + MECHANISM_LABELS.get(
                row_data["recommended_mechanism"],
                row_data["recommended_mechanism"],
            )
        )
        row = " & ".join(
            [
                latex_escape(regime_label),
                fmt(row_data["credit_heterogeneity"]),
                fmt(row_data["broadcast_ceiling_correlation"]),
                fmt(row_data["group_correlation"]),
                fmt(row_data["critic_correlation"]),
                fmt(row_data["critic_minus_group_correlation"]),
                latex_escape(reading),
            ]
        )
        lines.append(row + r" \\")
    lines.extend(
        [
            r"\midrule",
            r"\multicolumn{7}{@{}l@{}}{\footnotesize "
            + f"{result['summary']['cell_count']} cells; "
            + f"{result['summary']['critic_clear_cells']} critic clear, "
            + f"{result['summary']['group_clear_cells']} group clear, "
            + f"{result['summary']['near_tie_cells']} near ties."
            + r"}\\",
            r"\bottomrule",
            r"\end{tabularx}",
        ]
    )
    return "\n".join(lines)


PG_LABELS = {
    "reinforce_return": "REINFORCE",
    "sibling_loo_return": "Sibling LOO",
    "prefix_value_baseline": "Prefix baseline",
    "brpo_combined_baseline": "BRPO-style",
    "learned_value_td": "Learned value TD",
    "oracle_value_td": "Oracle-value TD",
    "vimpo_actor_equal_ref": r"$\pi=\pi_{\rm ref}$",
    "vimpo_actor_fixed_ref_near": r"fixed ref., near",
    "vimpo_actor_fixed_ref_mid": r"fixed ref., mid",
    "vimpo_actor_fixed_ref_far": r"fixed ref., far",
}


def build_policy_gradient_table(result: dict[str, Any]) -> str:
    lines = [
        "% Generated by scripts/build_latex_inputs.py; do not edit by hand.",
        r"\begin{tabular}{@{}L{2.75cm}rrrrrrr@{}}",
        r"\toprule",
        r"Estimator & Err. & Var. & Cos. & $\overline{\Delta J_b}$ & P5 $\Delta J_b$ & Neg. & Null $|\hat A|$ \\",
        r"\midrule",
    ]
    for estimator in result["estimators"]:
        metrics = estimator["metrics"]
        method = estimator["method"]
        row = " & ".join(
            [
                PG_LABELS.get(method, latex_escape(method)),
                fmt_pm(
                    metrics["relative_mean_error_norm"],
                    metrics["relative_mean_error_norm_ci95"],
                ),
                fmt_pm4(metrics["variance_trace"], metrics["variance_trace_ci95"]),
                fmt_pm(metrics["gradient_cosine"], metrics["gradient_cosine_ci95"]),
                fmt(metrics["batch_matched_kl_improvement_mean"]),
                fmt(metrics["batch_matched_kl_improvement_p05"]),
                fmt(metrics["batch_negative_update_probability"]),
                fmt(metrics["null_abs_credit_mean"]),
            ]
        )
        lines.append(row + r" \\")
    lines.extend(
        [
            r"\midrule",
            r"\multicolumn{8}{@{}l@{}}{\footnotesize "
            + f"$\\|g^\\star\\|={fmt(result['exact_gradient']['norm'])}$; "
            + f"base $R={fmt(result['exact_gradient']['base_return'])}$; "
            + f"{result['config']['replications']} replications. "
            + r"$\Delta J_b$: per-batch matched-KL."
            + r"}\\",
            r"\bottomrule",
            r"\end{tabular}",
        ]
    )
    return "\n".join(lines)


def build_policy_implied_table(result: dict[str, Any]) -> str:
    lines = [
        "% Generated by scripts/build_latex_inputs.py; do not edit by hand.",
        r"\begin{tabularx}{\linewidth}{@{}L{3.05cm}rrrrrY@{}}",
        r"\toprule",
        r"VIMPO-style diagnostic & Ref. KL & Err.$/\|g^\star\|$ & Cos. & $\Delta J$ & $r_A$ & Reading \\",
        r"\midrule",
    ]
    readings = {
        "vimpo_actor_equal_ref": "actor coefficient is zero at equal reference",
        "vimpo_actor_fixed_ref_near": "chosen path: direction fixed, magnitude mismatch changes",
        "vimpo_actor_fixed_ref_mid": "chosen path: direction fixed, magnitude mismatch changes",
        "vimpo_actor_fixed_ref_far": "chosen path: direction fixed; not full VIMPO performance",
    }
    for estimator in result["policy_implied_signals"]:
        metrics = estimator["metrics"]
        method = estimator["method"]
        row = " & ".join(
            [
                PG_LABELS.get(method, latex_escape(method)),
                fmt(estimator["reference_kl"]),
                fmt(metrics["relative_mean_error_norm"]),
                fmt(metrics["gradient_cosine"]),
                fmt(metrics["matched_kl_improvement"]),
                fmt(metrics["advantage_correlation"]),
                latex_escape(readings.get(method, "")),
            ]
        )
        lines.append(row + r" \\")
    lines.extend(
        [
        r"\midrule",
        r"\multicolumn{7}{@{}p{0.96\linewidth}@{}}{\footnotesize "
        r"Rows are policy-implied actor-coefficient alignment diagnostics, "
        r"not complete \textsc{VIMPO} algorithm performance or KL-regularized "
        r"objective comparisons."
        r"}\\",
            r"\bottomrule",
            r"\end{tabularx}",
        ]
    )
    return "\n".join(lines)


BASELINE_LABELS = {
    "group_mean": "Group mean",
    "prefix_budget": "Prefix budget",
    "brpo_combined": "BRPO-style",
    "critic_value": "Critic value",
}


def build_policy_baseline_table(result: dict[str, Any]) -> str:
    overall = result["position_diagnostics"]["overall"]
    lines = [
        "% Generated by scripts/build_latex_inputs.py; do not edit by hand.",
        r"\begin{tabular}{@{}lrrrr@{}}",
        r"\toprule",
        r"Baseline & Corr$(b_t,G_t)$ & Var$(G-b)$/Var$(G)$ & Score-wtd. resid. & Count \\",
        r"\midrule",
    ]
    for name in ["group_mean", "prefix_budget", "brpo_combined", "critic_value"]:
        row_data = overall[name]
        row = " & ".join(
            [
                latex_escape(BASELINE_LABELS[name]),
                fmt(row_data["corr_baseline_return"]),
                fmt(row_data["residual_variance_ratio"]),
                fmt(row_data["score_weighted_residual_second_moment"]),
                str(row_data["count"]),
            ]
        )
        lines.append(row + r" \\")
    lines.extend([r"\bottomrule", r"\end{tabular}"])
    return "\n".join(lines)


def build_selection_regret_table(result: dict[str, Any]) -> str:
    labels = {
        "audit_mse_cost": "Audit MSE+cost",
        "always_group": "Always group",
        "always_critic": "Always critic",
    }
    lines = [
        "% Generated by scripts/build_latex_inputs.py; do not edit by hand.",
        r"\begin{tabular}{@{}lrrrr@{}}",
        r"\toprule",
        r"Policy & Mean regret & Max regret & Accuracy & Critic rate \\",
        r"\midrule",
    ]
    for name in ["audit_mse_cost", "always_group", "always_critic"]:
        metrics = result["heldout_metrics"][name]
        row = " & ".join(
            [
                latex_escape(labels[name]),
                f"{metrics['mean_regret']:.5f}",
                f"{metrics['max_regret']:.5f}",
                fmt(metrics["selection_accuracy"]),
                fmt(metrics["critic_choice_rate"]),
            ]
        )
        lines.append(row + r" \\")
    lines.extend(
        [
            r"\midrule",
            r"\multicolumn{5}{@{}l@{}}{\footnotesize "
            + f"{result['config']['train_cell_count']} train cells, "
            + f"{result['config']['heldout_cell_count']} held-out cells; "
            + f"fitted $\\lambda={result['config']['fitted_lambda_cost']:.4f}$."
            + r"}\\",
            r"\bottomrule",
            r"\end{tabular}",
        ]
    )
    return "\n".join(lines)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--matrix-json",
        type=Path,
        default=Path("results/deep_matrix_20seed.json"),
    )
    parser.add_argument(
        "--variance-grid-json",
        type=Path,
        default=Path("results/variance_credit_grid_seed17.json"),
    )
    parser.add_argument(
        "--length-audit-json",
        type=Path,
        default=Path("results/length_imbalance_audit_seedset.json"),
    )
    parser.add_argument(
        "--anchor-coverage-json",
        type=Path,
        default=Path("results/anchor_coverage_audit_seedset.json"),
    )
    parser.add_argument(
        "--token-cost-json",
        type=Path,
        default=Path("results/token_cost_sensitivity_20seed.json"),
    )
    parser.add_argument(
        "--closed-loop-json",
        type=Path,
        default=Path("results/closed_loop_credit_training_10seed.json"),
    )
    parser.add_argument(
        "--closed-loop-low-coverage-json",
        type=Path,
        default=Path("results/closed_loop_credit_training_low_coverage_10seed.json"),
    )
    parser.add_argument(
        "--neural-generalization-json",
        type=Path,
        default=Path("results/neural_credit_generalization_seedset.json"),
    )
    parser.add_argument(
        "--sequence-policy-json",
        type=Path,
        default=Path("results/sequence_policy_training_seedset.json"),
    )
    parser.add_argument(
        "--phase-diagram-json",
        type=Path,
        default=Path("results/credit_phase_diagram_seedset.json"),
    )
    parser.add_argument(
        "--policy-gradient-json",
        type=Path,
        default=Path("results/policy_gradient_fidelity_seed13.json"),
    )
    parser.add_argument(
        "--selection-regret-json",
        type=Path,
        default=Path("results/selection_regret_seedset.json"),
    )
    parser.add_argument("--output-dir", type=Path, default=Path("paper/generated"))
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    result = json.loads(args.matrix_json.read_text())
    variance_grid = json.loads(args.variance_grid_json.read_text())
    length_audit = json.loads(args.length_audit_json.read_text())
    anchor_coverage = json.loads(args.anchor_coverage_json.read_text())
    token_cost = json.loads(args.token_cost_json.read_text())
    closed_loop = json.loads(args.closed_loop_json.read_text())
    closed_loop_low_coverage = json.loads(args.closed_loop_low_coverage_json.read_text())
    neural_generalization = json.loads(args.neural_generalization_json.read_text())
    sequence_policy = json.loads(args.sequence_policy_json.read_text())
    phase_diagram = json.loads(args.phase_diagram_json.read_text())
    policy_gradient = json.loads(args.policy_gradient_json.read_text())
    selection_regret = json.loads(args.selection_regret_json.read_text())
    args.output_dir.mkdir(parents=True, exist_ok=True)

    macros = args.output_dir / "result_macros.tex"
    table = args.output_dir / "deep_matrix_table.tex"
    variance_credit = args.output_dir / "variance_credit_table.tex"
    anchor_coverage_table = args.output_dir / "anchor_coverage_table.tex"
    length_imbalance = args.output_dir / "length_imbalance_table.tex"
    token_cost_table = args.output_dir / "token_cost_table.tex"
    closed_loop_table = args.output_dir / "closed_loop_training_table.tex"
    neural_generalization_table = args.output_dir / "neural_generalization_table.tex"
    sequence_policy_table = args.output_dir / "sequence_policy_table.tex"
    credit_phase_table = args.output_dir / "credit_phase_table.tex"
    policy_gradient_table = args.output_dir / "policy_gradient_table.tex"
    policy_implied_table = args.output_dir / "policy_implied_table.tex"
    policy_baseline_table = args.output_dir / "policy_baseline_table.tex"
    selection_regret_table = args.output_dir / "selection_regret_table.tex"
    macros.write_text(build_macros(result) + "\n")
    table.write_text(build_table(result) + "\n")
    variance_credit.write_text(build_variance_credit_table(variance_grid) + "\n")
    anchor_coverage_table.write_text(
        build_anchor_coverage_table(anchor_coverage) + "\n"
    )
    length_imbalance.write_text(build_length_imbalance_table(length_audit) + "\n")
    token_cost_table.write_text(build_token_cost_table(token_cost) + "\n")
    closed_loop_table.write_text(
        build_closed_loop_table(closed_loop, closed_loop_low_coverage) + "\n"
    )
    neural_generalization_table.write_text(
        build_neural_generalization_table(neural_generalization) + "\n"
    )
    sequence_policy_table.write_text(build_sequence_policy_table(sequence_policy) + "\n")
    credit_phase_table.write_text(build_credit_phase_table(phase_diagram) + "\n")
    policy_gradient_table.write_text(build_policy_gradient_table(policy_gradient) + "\n")
    policy_implied_table.write_text(build_policy_implied_table(policy_gradient) + "\n")
    policy_baseline_table.write_text(build_policy_baseline_table(policy_gradient) + "\n")
    selection_regret_table.write_text(
        build_selection_regret_table(selection_regret) + "\n"
    )

    print(f"wrote {macros}")
    print(f"wrote {table}")
    print(f"wrote {variance_credit}")
    print(f"wrote {anchor_coverage_table}")
    print(f"wrote {length_imbalance}")
    print(f"wrote {token_cost_table}")
    print(f"wrote {closed_loop_table}")
    print(f"wrote {neural_generalization_table}")
    print(f"wrote {sequence_policy_table}")
    print(f"wrote {credit_phase_table}")
    print(f"wrote {policy_gradient_table}")
    print(f"wrote {policy_implied_table}")
    print(f"wrote {policy_baseline_table}")
    print(f"wrote {selection_regret_table}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
