#!/usr/bin/env python3
"""Generate LaTeX result inputs from canonical experiment JSON."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


SELECTED_CASES = [
    "horizon_04_baseline",
    "horizon_16_long_wait",
    "critic_budget_002_full",
    "critic_budget_128_full",
    "observability_blind",
    "blind_undercovered_counterexample",
    "sparse_hard_group08",
]


def latex_escape(value: str) -> str:
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    return "".join(replacements.get(char, char) for char in value)


def fmt(value: float) -> str:
    return f"{value:.3f}"


def macro_line(name: str, value: str | int | float) -> str:
    return rf"\newcommand{{\{name}}}{{{value}}}"


def build_macros(result: dict[str, Any]) -> str:
    overall = result["overall"]
    lines = [
        "% Generated by scripts/build_latex_inputs.py; do not edit by hand.",
        macro_line("DeepSeedCount", result["seed_count"]),
        macro_line("DeepCaseCount", result["case_count"]),
        macro_line("DeepMeanCriticWins", overall["critic_wins_by_mean_correlation"]),
        macro_line("DeepMeanGroupWins", overall["group_wins_by_mean_correlation"]),
        macro_line("DeepClearCriticCases", overall["clear_critic_cases_by_ci95"]),
        macro_line("DeepNearTieCases", overall["near_tie_cases_by_ci95"]),
        macro_line("DeepClearGroupCases", overall["clear_group_cases_by_ci95"]),
        macro_line("DeepMeanDeltaCorrelation", fmt(overall["mean_delta_correlation"])),
        "",
    ]
    return "\n".join(lines)


def build_table(result: dict[str, Any]) -> str:
    cases = {case["case_name"]: case for case in result["cases"]}
    lines = [
        "% Generated by scripts/build_latex_inputs.py; do not edit by hand.",
        r"\begin{tabular}{@{}lrrrrl@{}}",
        r"\toprule",
        r"Case & Group $r$ & Critic $r$ & Delta & CI & Reading \\",
        r"\midrule",
    ]
    for case_name in SELECTED_CASES:
        case = cases[case_name]
        row = " & ".join(
            [
                latex_escape(case["case_name"]),
                fmt(case["mean_group_correlation"]),
                fmt(case["mean_critic_correlation"]),
                fmt(case["mean_critic_minus_group_correlation"]),
                rf"$\pm${fmt(case['ci95_critic_minus_group_correlation'])}",
                latex_escape(case["evidence_by_ci95"].replace("_", " ")),
            ]
        )
        lines.append(row + r" \\")
    lines.extend([r"\bottomrule", r"\end{tabular}", ""])
    return "\n".join(lines)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--matrix-json",
        type=Path,
        default=Path("results/deep_matrix_20seed.json"),
    )
    parser.add_argument("--output-dir", type=Path, default=Path("paper/generated"))
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    result = json.loads(args.matrix_json.read_text())
    args.output_dir.mkdir(parents=True, exist_ok=True)

    macros = args.output_dir / "result_macros.tex"
    table = args.output_dir / "deep_matrix_table.tex"
    macros.write_text(build_macros(result) + "\n")
    table.write_text(build_table(result) + "\n")

    print(f"wrote {macros}")
    print(f"wrote {table}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
